### ISSUE TITLE
autoRefresh()时，迅速连击屏幕，会取消刷新

### ISSUE THREAD

**Issue by conghuahuadan** [anzaizai/EasyRefreshLayout#12]
你好，打开Demo第一个only pull down refresh的activity，迅速连击屏幕，会取消自动刷新

**Comment by githubzaibao** [comment]
你好，我这里重复测试了多次，还是无法重现你说的问题，这个问题现在解决了么？

**Comment by conghuahuadan** [comment]
没有，在真机和模拟器测试都有问题，在点击第一个activity的时候，一直连击屏幕就看到效果了。

![gif_2](https://cloud.githubusercontent.com/assets/20864280/24964660/754218e4-1fd4-11e7-9eca-ee84ba7ba8fd.gif)

**Comment by kennir** [comment]
最新的版本还是有这个问题
