### ISSUE TITLE
1.1.2  leaks 报内存溢出~

### ISSUE THREAD

**Issue by BinarySatan** [anzaizai/EasyRefreshLayout#13]
easyEvent  与 runnable

**Comment by BinarySatan** [comment]
* GC ROOT static android.os.AsyncTask.sHandler
* references android.os.AsyncTask$InternalHandler.mQueue
* references android.os.MessageQueue.mMessages
* references android.os.Message.callback
* references com.ajguan.library.EasyRefreshLayout$1.this$0 (anonymous implementation of java.lang.Runnable)
* references com.ajguan.library.EasyRefreshLayout.easyEvent

**Comment by githubzaibao** [comment]
你好，该项目我也用在了公司的产品中，还没发生过oom，发生oom的原因很多，处罚GC程序启动原因也很多，我会仔细检查下代码，或许只是在我这个节点触发了GC操作，原因也可能是其他方，我们一起解决找一下，最近我的产品也遇到了OOM问题，你可以看下这个http://cherylgood.cn/20170411/83

**Comment by githubzaibao** [comment]
感谢你的反馈，谢谢

**Comment by BinarySatan** [comment]
好的
