### ISSUE TITLE
禁用下拉刷新后，上拉加载不能用

### ISSUE THREAD

**Issue by liulance** [anzaizai/EasyRefreshLayout#17]
下载源码运行 ，ONLY PULL UP LOADINNG 界面，不能加载更多，        easyRefreshLayout.setEnablePullToRefresh(false);
设置这个属性后。上拉加载也用不了

**Comment by githubzaibao** [comment]
设置为true，这个是下拉刷新的

**Comment by micki-zhou** [comment]
同样的问题

**Comment by liulance** [comment]
我要禁用下拉刷新，禁用下拉刷新后，上拉加载更多就用不了

**Comment by githubzaibao** [comment]
你好，在1.2.0版本中已修复，感谢你的反馈
