### ISSUE TITLE
下拉刷新背景不能全覆盖

### ISSUE THREAD

**Issue by lk5103613** [anzaizai/EasyRefreshLayout#19]
如下图
![360 20170707155537456](https://user-images.githubusercontent.com/7112274/27948596-ee692316-632c-11e7-8266-9858c7764950.jpg)
下拉刷新的背景并不能全覆盖

**Comment by lk5103613** [comment]
对不起，是我看的不仔细，把EasyRefreshLayou的背景设置成和下拉背景相同即可

![360 20170707165725521](https://user-images.githubusercontent.com/7112274/27950844-61d0cb08-6335-11e7-824d-1f9948bd0cc7.jpg)

**Comment by githubzaibao** [comment]
嗯嗯，最新版本1.2.0，欢迎使用
