### ISSUE TITLE
单独实现加载更多bug

### ISSUE THREAD

**Issue by sweet2o09** [anzaizai/EasyRefreshLayout#20]
OnlyLoadingActivity.java里面因为easyRefreshLayout.setEnablePullToRefresh(false);导致加载更多功能无法实现,但是开启的话又会有下拉刷新,建议两个分开判断,另外就是BRVAH版本估计需要更新下

**Comment by githubzaibao** [comment]
好的，感谢你的反馈，上拉加载跟下拉刷新目前是分开判断的，

**Comment by githubzaibao** [comment]
你好，1.2.0版本已修复该问题，感谢你的反馈
