### ISSUE TITLE
和BaseRecyclerViewAdapterHelper结合使用的问题

### ISSUE THREAD

**Issue by h390** [anzaizai/EasyRefreshLayout#22]
现在产品的需求是需要自定义的一个下拉的刷新头，上拉的时候需要在最后一个item的底部加入脚布局。
所以现在就有一个需求是应用easyrefreshlayout的下拉刷新，又需要应用到BaseRecyclerViewAdapterHelper的上拉加载。请问这样的需求，需要在EasyRefreshLayout中怎么设置呢？

**Comment by githubzaibao** [comment]
我用1.2.0版本的测试了，发现可以兼容的

**Comment by githubzaibao** [comment]
adapter.setEnableLoadMore(true);
        adapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                Log.i(TAG, ">>>>");
                List<String> list = new ArrayList<>();
                for (int i = 0; i < 5; i++) {
                    list.add("this is  new load data >>>>" + new Date().toLocaleString());
                }

                adapter.getData().addAll(list);
                adapter.notifyDataSetChanged();
                adapter.loadMoreComplete();


        }
    },recyclerView);

**Comment by githubzaibao** [comment]
easyRefreshLayout.setEnableLoadMore(false);
