### ISSUE TITLE
作者是否可以增加预加载功能？

### ISSUE THREAD

**Issue by ljackChen001** [anzaizai/EasyRefreshLayout#24]
使用BaseRecyclerViewAdapterHelper     NestedScrollView 嵌套RecyclerView  会无限触发上拉加载，作者看是否可以支持预加载？

**Comment by lucklygaj** [comment]
Ok了。升级到1.3.1即可

**Comment by ljackChen001** [comment]
NestedScrollView  嵌套RecyclerView  还是没法使用，单独使用RecyclerView  BaseRecyclerViewAdapterHelper  自带的也可以实现

**Comment by lucklygaj** [comment]
实现预加载是通过recyclerView本身的滚动监听器实现的，如果一开始就全部展开了，是不会触发的

**Comment by ljackChen001** [comment]
NestedScrollView  嵌套RecyclerView   之后  recyclerView.setNestedScrollingEnabled(false);  滑动都交给了NestedScrollView    所以滑动的时候  上拉根本就会没有效果

**Comment by lucklygaj** [comment]
NestedScrollView 跟ScrollView作用基本一样，你RecyclerView的滚动事件如果被拦截了，这个预加载肯定受影响
