### ISSUE TITLE
是否可以让加载更多不覆盖最后一个view

### ISSUE THREAD

**Issue by baby2431** [anzaizai/EasyRefreshLayout#26]
作者~你好~
近期在使用你的这个控件的时候，发现，加载更多的界面，会覆盖住最后一个Item 不知道如何设置，可以让这个不覆盖？
and 可以在xml中设置刷新样式和加载更多的样式吗？
不胜感激

**Comment by lucklygaj** [comment]
你可以设置背景透明，这样子就不覆盖了，如果想让其自动顶起最后一个item，需要通过自定义recyclverView或者adapter来实现了，刷新样式可以通过自定义加载更多View，通过实现接口即可
