### ISSUE TITLE
点击加载更多的view没有反应

### ISSUE THREAD

**Issue by idealgn** [anzaizai/EasyRefreshLayout#31]
扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差扩展性好差

**Comment by lucklygaj** [comment]
不知道你说的扩展性是指什么？你可以直接实现接口自定义相关view的样式与行为

**Comment by idealgn** [comment]
这个我实在没找到怎么去自定义刷新头和底部局，实在太着急了，项目直接拿来用，却找不到怎么改的地方，抱歉！
发自网易邮箱大师
在2017年10月10日 09:46，GajAngels 写道： 不知道你说的扩展性是指什么？你可以直接实现接口自定义相关view的样式与行为

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/anzaizai/EasyRefreshLayout","title":"anzaizai/EasyRefreshLayout","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/anzaizai/EasyRefreshLayout"}},"updates":{"snippets":[{"icon":"PERSON","message":"@githubzaibao in #31: 不知道你说的扩展性是指什么？你可以直接实现接口自定义相关view的样式与行为"}],"action":{"name":"View Issue","url":"https://github.com/anzaizai/EasyRefreshLayout/issues/31#issuecomment-335335411"}}}

**Comment by lucklygaj** [comment]
step 4

Customizable pull-down refresh head view

You only need to create a view to implement the RefreshVIew interface
Set the custom view to Easy RefreshLayout
easyRefreshLayout.setRefreshHeadView(customizabaleView);

Customizable pull-up load footer view

You only need to create a view to implement the ILoadMoreView interface
Set the custom view to Easy RefreshLayout
easyRefreshLayout.setLoadMoreView(customizabaleView);

自定义的view需要实现相应的接口ILoadMoreView与IRefreshHeader

**Comment by idealgn** [comment]
Very good,thank you!
发自网易邮箱大师
在2017年10月12日 08:56，GajAngels 写道： step 4
Customizable pull-down refresh head view
You only need to create a view to implement the RefreshVIew interface
Set the custom view to Easy RefreshLayout
easyRefreshLayout.setRefreshHeadView(customizabaleView);
Customizable pull-up load footer view
You only need to create a view to implement the ILoadMoreView interface
Set the custom view to Easy RefreshLayout
easyRefreshLayout.setLoadMoreView(customizabaleView);
自定义的view需要实现相应的接口ILoadMoreView与IRefreshHeader

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/anzaizai/EasyRefreshLayout","title":"anzaizai/EasyRefreshLayout","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/anzaizai/EasyRefreshLayout"}},"updates":{"snippets":[{"icon":"PERSON","message":"@githubzaibao in #31: step 4\r\n\r\nCustomizable pull-down refresh head view\r\n\r\nYou only need to create a view to implement the RefreshVIew interface\r\nSet the custom view to Easy RefreshLayout\r\neasyRefreshLayout.setRefreshHeadView(customizabaleView);\r\n\r\nCustomizable pull-up load footer view\r\n\r\nYou only need to create a view to implement the ILoadMoreView interface\r\nSet the custom view to Easy RefreshLayout\r\neasyRefreshLayout.setLoadMoreView(customizabaleView);\r\n\r\n自定义的view需要实现相应的接口ILoadMoreView与IRefreshHeader"}],"action":{"name":"View Issue","url":"https://github.com/anzaizai/EasyRefreshLayout/issues/31#issuecomment-335989631"}}}
