### ISSUE TITLE
加载更多问题

### ISSUE THREAD

**Issue by farrywen** [anzaizai/EasyRefreshLayout#4]
加载更多时，将RecyclerView滑到顶部，会显示不完整。

**Comment by githubzaibao** [comment]
我运行了示例代码，没发现有问题，可否提供下截图和代码

**Comment by farrywen** [comment]
demo的代码
![1319d586-7bee-44b0-ac92-6dfc8fcf733e](https://cloud.githubusercontent.com/assets/5836654/20590942/f638dea6-b260-11e6-87a9-bf395c82098f.png)

**Comment by githubzaibao** [comment]
感谢你的反馈，这确实是实现上的缺陷，我会尽快修复

**Comment by farrywen** [comment]
还有一个bug如图
![eca3e734-6fcd-40e4-94ad-727d5c230c29](https://cloud.githubusercontent.com/assets/5836654/20591271/af30300c-b262-11e6-853f-8b67b695c90a.png)

**Comment by githubzaibao** [comment]
ok,非常感谢

**Comment by githubzaibao** [comment]
最新已修复
