### ISSUE TITLE
加载更多和下拉刷新成功后取消动画

### ISSUE THREAD

**Issue by SmallDream** [anzaizai/EasyRefreshLayout#7]
现在下拉刷新成功后，会显示刷新成功，然后慢慢回弹上去。有办法取消这个效果吗？想直接弹上去不要动画效果。
加载更多也是同样的情况

**Comment by githubzaibao** [comment]
上拉加载可以直接消失，有个closeLoadView方法，下刷新可以设置动画时间控制

**Comment by SmallDream** [comment]
setHideLoadViewAnimatorDuration(0),之后，刷新成功确实不显示直接消失了。但之后回弹动画还在。 
setScrollToTopDuration(0)的话，会出现无法回弹的bug

**Comment by SmallDream** [comment]
调用了closeLoadView还需要调用loadMoreComplete了吗. 现在只调用closeLoadVIew,回弹动画是没有了，但recycleview还是会滚到原本的位置。 而我希望recyleview位置不变，这样用户就能看到确实加载出来了内容

**Comment by githubzaibao** [comment]
这个，可能你要手动调用下recyclerview让他上滚一个位置，那个当时没考虑到，感谢你的反馈

**Comment by SmallDream** [comment]
大致希望实现的效果类似今日头条，那边是成功后直接消失的。
多谢作者及时答复。我自己也去调调看 : ）

**Comment by githubzaibao** [comment]
你的问题解决了么，

**Comment by SmallDream** [comment]
没有。暂时先不搞这个了。 - -
