### ISSUE TITLE
scrollView嵌套EasyRefrechLayout问题

### ISSUE THREAD

**Issue by yangzhenqi** [anzaizai/EasyRefreshLayout#8]
scrollView嵌套EasyRefrechLayot时，easyRefrechLayout不显示了

**Comment by githubzaibao** [comment]
是怎么个不显示法，能贴个代码么？感谢你的反馈

**Comment by micki-zhou** [comment]
同样遇到这个问题，
<ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

                     <com.ajguan.library.EasyRefreshLayout
                          android:id="@+id/er_load_more"
                          android:layout_width="match_parent"
                          android:layout_height="match_parent">

                                  <android.support.v7.widget.RecyclerView
                                    android:id="@+id/rv_comment"
                                   android:layout_width="match_parent"
                                    android:layout_height="match_parent"
                                   android:background="@color/bg_grey"
                                    android:visibility="gone" />
            </com.ajguan.library.EasyRefreshLayout>
         </LinearLayout>
</ScrollView>

像这样的话，不仅easyRefreshLayout不显示了，连RecyclerView都不显示了。去掉easyRefreshLayout,一切正常。

**Comment by micki-zhou** [comment]
android:visibility="gone" 这个是我自己逻辑里有判断，不是因为这个不显示哈

**Comment by micki-zhou** [comment]
最外层还有个ScrollView,不知道为什么发出来就没了

**Comment by githubzaibao** [comment]
感谢你的反馈，我现在看下

**Comment by githubzaibao** [comment]
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
你设置成匹配父布局看下

**Comment by micki-zhou** [comment]
什么意思，不是很明白 @githubzaibao

**Comment by githubzaibao** [comment]
已重现该问题，我先研究研究，解决了会及时联系你

**Comment by micki-zhou** [comment]
好的，谢谢 @githubzaibao

**Comment by gwwnha** [comment]
不知掉这个问题解决了怎么样了，同样遇到了

**Comment by githubzaibao** [comment]
有个方案解决了，但有瑕疵，还在coding

**Comment by githubzaibao** [comment]
关于嵌套ScrollView，目前想到两种解决方法，一、将scrollView的android:layout_height="math_parent">
二、在EasyRefreshLayout的onMeasure方法中调用        super.onMeasure(widthMeasureSpec,传入指定的高度);
